// Curated keyword + handle-token lexicon (data only).
// Seeded into project_tags via services/tagTools.seedKeywordsFromLexicon
// or `npm run tag:seed-keywords`.

/**
 * Keyword lexicon keyed by tag slug. A match on ANY entry tags the account with
 * that slug. Strings are whole-word matched; regexes are used as-is. `other` /
 * `unknown` are intentionally omitted (not inferable from a bio).
 */
export const KEYWORDS: Record<string, (string | RegExp)[]> = {
  launchpad: [
    "launchpad", "launch pad", "token launch", "ido", "ico", "ieo", "igo", "ino",
    "ido platform", "fair launch", "token sale", "presale", "pre-sale", "pre sale",
    "bonding curve", "pump.fun", "pumpfun", "letsbonk", "bonk.fun", "moonshot",
    "launchpool", "launch pool", "initial dex offering", "token generation event",
    "tge", "public sale", "private sale", "seed sale", "community sale",
    "token generation", "liquidity bootstrap", "lbp", "pad launch",
    "meme launchpad", "token launchpad", "fundraising platform",
  ],
  l1: [
    "layer 1", "layer-1", "layer1", "l1 blockchain", "l1 chain", "base layer",
    "monolithic blockchain", "smart contract platform", "evm chain",
    "evm-compatible", "evm compatible", "alt l1", "alt-l1", "sovereign chain",
    "modular blockchain", "appchain", "app chain", "sovereign l1",
    "high throughput chain", "parallel execution", "execution layer",
    /\bl1\b/,
  ],
  l2: [
    "layer 2", "layer-2", "layer2", "rollup", "rollups", "optimistic rollup",
    "zk rollup", "zk-rollup", "zkrollup", "validium", "scaling solution",
    "ethereum scaling", "op stack", "opstack", "superchain", "arbitrum orbit",
    "based rollup", "sovereign rollup", "zk stack", "polygon cdk", "cdk chain",
    "settlement layer", "l2 chain", "optimistic", "fraud proof", "validity proof",
    /\bl2\b/,
  ],
  meme: [
    "meme", "memecoin", "memecoins", "meme coin", "meme coins", "memes",
    "meme token", "dog coin", "dogcoin", "shitcoin", "degen coin",
    "community coin", "meme culture", "animal coin", "cult coin",
    "meme season", "meme meta", "frog coin", "cat coin",
    /\bpepe\b/, /\bdoge\b/, /\bwif\b/, /\bbonk\b/, /\bmog\b/, /\bpnut\b/,
  ],
  rwa: [
    "rwa", "rwas", "real world asset", "real-world asset", "real world assets",
    "tokenized asset", "tokenized assets", "tokenization", "asset tokenization",
    "tokenized treasuries", "tokenized treasury", "tokenized real estate",
    "tokenize real world", "tokenized fund", "tokenized securities",
    "tokenized stocks", "tokenized bonds", "tokenized commodities",
    "tokenized t-bills", "tokenized credit", "on-chain treasuries",
    "real world yield", "off-chain assets", "private credit",
  ],
  defi: [
    "defi", "de-fi", "decentralized finance", "amm", "automated market maker",
    "liquidity pool", "liquidity protocol", "money market", "yield farming",
    "yield aggregator", "yield optimizer", "vault", "vaults", "farming",
    "staking protocol", "collateral", "cdp", "over-collateralized",
    "leveraged yield", "defi protocol", "on-chain finance", "money lego",
    "liquidity mining", "auto-compound", "auto-compounding", "restaked yield",
    /\btvl\b/,
  ],
  ai: [
    "ai", /\bartificial intelligence\b/, "machine learning", "deep learning",
    "llm", "llms", "large language model", "neural network", "neural nets",
    "generative ai", "gen ai", "genai", "ai model", "ai models",
    "ai infrastructure", "ai compute", "ai inference", "ai-powered",
    "ai powered", "ai native", "ai-native", "ai protocol", "foundation model",
    "open source ai", "open-source ai", "ai training", "decentralized ai",
    "ai crypto", "crypto ai", /\bgpt\b/, /\bml\b/,
  ],
  derivatives: [
    "derivatives", "derivative", "options trading", "options protocol",
    "on-chain options", "options vault", "futures", "structured products",
    "synthetic assets", "synthetic asset", "synths", "options dex",
    "crypto options", "volatility trading", "power perpetuals",
  ],
  nft: [
    "nft", "nfts", "non-fungible", "non fungible", "mint", "minting",
    "mint live", "public mint", "free mint", "wl mint", "whitelist mint",
    "collectible", "collectibles", "pfp", "pfps", "digital art",
    "generative art", "art collection", "1/1", "one of one", "opensea",
    "magic eden", "blur", "jpeg", "jpegs", "profile picture project",
    "nft collection", "nft project", "nft marketplace", "nft drop",
    "collection drop", "reveal", "minting soon", "mint date",
  ],
  "lending-yield": [
    "lending", "lend", "borrow", "borrowing", "yield", "staking rewards",
    "earn yield", "lending protocol", "lending market", "lending platform",
    "interest rate", "supply and borrow", "credit protocol", "money market",
    "undercollateralized lending", "yield-bearing", "yield bearing",
    "flash loan", "flash loans", "borrow against", "fixed rate lending",
    "variable rate", "supply apy", "borrow apy",
  ],
  depin: [
    "depin", "decentralized physical", "physical infrastructure",
    "decentralized wireless", "decentralized compute", "decentralized storage",
    "decentralized gpu", "gpu network", "wireless network", "sensor network",
    "decentralized energy", "iot network", "dephy", "physical infra",
    "helium", "render network", "filecoin", "akash", "edge compute",
    "device network", "hardware network", "node sale", "miner network",
  ],
  desci: [
    "desci", "decentralized science", "science dao", "biotech dao",
    "research dao", "longevity", "decentralized research", "open science",
    "scientific research", "biotech", "drug discovery", "ip-nft", "ip nft",
    "research funding", "lab dao",
  ],
  socialfi: [
    "socialfi", "social-fi", "social finance", "social token", "social tokens",
    "decentralized social", "web3 social", "creator economy", "social graph",
    "social network protocol", "friend.tech", "friendtech", "social app",
    "farcaster", "lens protocol", "creator coin", "tipping protocol",
    "attention economy", "social layer",
  ],
  tools: [
    "toolkit", "dev tools", "developer tools", "sdk", "analytics tool",
    "analytics platform", "dashboard", "trading tools", "trading bot",
    "telegram bot", "portfolio tracker", "block explorer", "charting",
    "terminal", "screener", "token screener", "sniping bot", "sniper bot",
    "trading terminal", "no-code", "no code", "automation tool",
    "on-chain analytics", "wallet tracker", "copy trading", "smart money",
    "dex tools", "dextools", "mev bot", "arbitrage bot",
  ],
  "ai-agents": [
    "ai agent", "ai agents", "autonomous agent", "autonomous agents",
    "agentic", "ai-agent", "agent framework", "agent swarm", "agent economy",
    "autonomous ai", "ai companion", "agentic ai", "ai swarm", "multi-agent",
    "agent-to-agent", "eliza framework", "elizaos", "virtuals", "agent launchpad",
    "agent marketplace", "on-chain agent", "trading agent", "agent", "agents",
  ],
  "infra-data": [
    "infrastructure", "indexer", "indexing", "data availability",
    "node infrastructure", "node operator", "validator", "middleware",
    "data layer", "data protocol", "on-chain data", "blockchain data",
    "subgraph", "api infrastructure", "compute layer", "sequencer",
    "co-processor", "coprocessor", "data infrastructure", "shared sequencer",
    "restaking infrastructure", "eigenlayer", "avs", "actively validated",
    /\brpc\b/, /\bda layer\b/,
  ],
  "dao-community": [
    "dao", "daos", "governance", "community-owned", "community owned",
    "on-chain governance", "decentralized autonomous", "governance token",
    "on-chain voting", "treasury management", "collective", "guild",
    "community dao", "governance protocol", "snapshot voting", "delegate",
    "delegates", "proposal voting", "community treasury",
  ],
  dex: [
    "dex", "dexs", "dexes", "decentralized exchange", "swap", "swaps",
    "spot trading", "spot dex", "orderbook dex", "order book", "clob",
    "concentrated liquidity", "liquidity aggregator", "dex aggregator",
    "trading protocol", "spot exchange", "amm dex", "token swap",
    "swap protocol", "limit order", "intent-based", "intent based",
  ],
  gambling: [
    "gambling", "casino", "betting", "sportsbook", "lottery", "dice",
    "roulette", "wager", "gamble", "igaming", "on-chain casino",
    "degen casino", "coin flip", "coinflip", "jackpot", "raffle",
    "provably fair", "crypto casino", "sports betting", "prediction betting",
  ],
  stablecoin: [
    "stablecoin", "stablecoins", "stable coin", "stable coins", "pegged",
    "usd-pegged", "usd pegged", "dollar-backed", "dollar backed",
    "algorithmic stablecoin", "yield-bearing stablecoin", "synthetic dollar",
    "decentralized stablecoin", "stablecoin protocol", "usd0", "usde",
    "on-chain dollar", "crypto dollar",
  ],
  "btc-eco": [
    "bitcoin", "ordinals", "inscriptions", "brc-20", "brc20", "brc-721",
    "runes", "rune protocol", "bitcoin l2", "bitcoin layer 2", "stacks",
    "taproot", "bitcoin defi", "bitcoin ecosystem", "satoshis", "bitcoin nfts",
    "babylon", "bitcoin staking", "btc staking", "bitcoin restaking",
    "lightning network", "rgb protocol", /\bbtc\b/, /\bbrc\b/, /\bsats\b/,
  ],
  metaverse: [
    "metaverse", "virtual world", "virtual worlds", "virtual reality",
    "augmented reality", "open world", "3d world", "immersive world",
    "digital world", "virtual land", "spatial computing", "virtual estate",
    "avatar world", /\bvr\b/, /\bar\b/,
  ],
  "cex-cefi": [
    "cex", "centralized exchange", "cefi", "crypto exchange", "trading platform",
    "custodial exchange", "order matching", "spot and futures exchange",
    "crypto broker", "exchange listing", "spot exchange",
  ],
  "investment-entity": [
    "investment firm", "asset management", "investment entity", "asset manager",
    "investment dao", "portfolio management", "wealth management",
    "capital management", "investment platform", "digital asset manager",
    "family office", "proprietary trading", "prop trading",
  ],
  gamefi: [
    "gamefi", "game-fi", "gaming", "play to earn", "play-to-earn", "p2e",
    "web3 game", "web3 gaming", "web3 games", "blockchain game",
    "blockchain gaming", "on-chain game", "on-chain gaming", "move to earn",
    "move-to-earn", "gaming guild", "game economy", "nft game", "autobattler",
    "mmo", "mmorpg", "free to play", "play and earn", "telegram game",
    "ton game", "mini game", "play", "rpg", "game",
  ],
  "news-media": [
    "news", "media outlet", "newsletter", "journalism", "magazine", "podcast",
    "media company", "crypto media", "editorial", "press", "media platform",
    "daily alpha", "research and news", "content platform", "alpha calls",
    "market research", "crypto research", "on-chain research",
  ],
  services: [
    "consulting", "agency", "service provider", "marketing agency",
    "development agency", "audit firm", "auditing", "security audit",
    "kol agency", "pr agency", "advisory", "dev shop", "growth agency",
    "community management", "smart contract audit", "audits",
    "tokenomics design", "go-to-market", "gtm agency", "kol marketing",
  ],
  defai: [
    "defai", "defi ai", "ai defi", "defi agent", "ai-powered defi",
    "autonomous defi", "ai trading agent", "agentic defi", "ai yield",
    "ai portfolio", "autonomous yield",
  ],
  "nft-fi": [
    "nftfi", "nft-fi", "nft lending", "nft finance", "nft-backed",
    "nft mortgage", "nft liquidity", "fractionalized nft", "nft perps",
    "nft derivatives", "nft financialization", "floor perps", "nft collateral",
    "borrow against nft",
  ],
  "multi-chain": [
    "multichain", "multi-chain", "cross-chain", "cross chain", "omnichain",
    "interoperability", "interoperable", "chain-agnostic", "chain agnostic",
    "any chain", "all chains", "chain abstraction", "cross-chain protocol",
    "universal chain", "chain-abstracted", "intent routing",
  ],
  perps: [
    "perps", "perp", "perpetuals", "perpetual futures", "perpetual swap",
    "perp dex", "perps dex", "perpetual dex", "perpetual exchange",
    "on-chain perps", "decentralized perps", "perp trading", "leverage trading",
    "crypto futures", "margin trading", "funding rate",
  ],
  funds: [
    "fund", "funds", "hedge fund", "liquidity fund", "index fund",
    "crypto fund", "on-chain fund", "tokenized fund", "quant fund",
    "venture fund", "liquid fund", "trading fund",
  ],
  "erc-404": ["erc-404", "erc404", "404 token", "hybrid token standard"],
  studios: [
    "game studio", "creative studio", "dev studio", "development studio",
    "studios", "animation studio", "design studio", "web3 studio",
    "gaming studio", "venture studio", "product studio", "content studio",
  ],
  lrt: [
    "lrt", "liquid restaking", "liquid restaking token", "restaking token",
    "restaked eth", "eigenlayer restaking", "restaking protocol",
    "restake", "restaking", "liquid restaked",
  ],
  oracles: [
    "oracle", "oracles", "price feed", "price feeds", "data oracle",
    "decentralized oracle", "oracle network", "off-chain data", "data feeds",
    "price oracle", "oracle protocol", "verifiable data", "oracle middleware",
  ],
  vc: [
    "venture capital", "vc firm", "venture firm", "early-stage investor",
    "early stage investor", "venture fund", "seed investor",
    "venture capitalist", "we invest in", "we back", "backing founders",
    "crypto vc", "web3 vc", "thesis-driven", "seed stage", /\bvc\b/,
  ],
  incubators: [
    "incubator", "incubators", "incubation", "incubating",
    "startup incubator", "project incubator", "web3 incubator",
  ],
  mms: [
    "market maker", "market making", "market makers", "liquidity provider",
    "liquidity providers", "liquidity provision", "designated market maker",
    "otc desk", "otc trading", "liquidity desk",
  ],
  accelerators: [
    "accelerator", "accelerators", "accelerator program", "startup accelerator",
    "growth accelerator", "web3 accelerator", "cohort program",
  ],
  wallet: [
    "wallet", "wallets", "self-custody", "self custody", "non-custodial",
    "non-custodial wallet", "custodial wallet", "hardware wallet",
    "smart wallet", "mpc wallet", "seed phrase", "crypto wallet", "web3 wallet",
    "embedded wallet", "account abstraction", "aa wallet", "passkey wallet",
    "smart account", "intent wallet",
  ],
  "erc-314": ["erc-314", "erc314", "314 standard"],
  lst: [
    "lst", "liquid staking", "liquid staking token", "staked eth",
    "liquid staked", "staking derivative", "liquid stake", "staking as a service",
    /\bsteth\b/, /\brseth\b/,
  ],
  predict: [
    "prediction market", "prediction markets", "predict market",
    "predictions market", "betting market", "forecast market", "polymarket",
    "event contracts", "opinion trading", "event trading", "forecasting",
    "binary market", "outcome market",
  ],
  bridge: [
    "bridge", "bridges", "cross-chain bridge", "token bridge", "bridging",
    "asset bridge", "interoperability bridge", "cross-chain messaging",
    "message passing", "canonical bridge", "trustless bridge",
    "native bridge", "liquidity bridge",
  ],
  robotics: [
    "robotics", "robot", "robots", "humanoid", "humanoid robot", "embodied ai",
    "autonomous machines", "physical ai", "robot economy", "autonomous robot",
  ],
  x402: [
    "x402", "x-402", "http 402", "machine payments", "agentic payments",
    "pay per request", "micropayments protocol",
  ],
  privacy: [
    "privacy", "private transactions", "zero-knowledge", "zero knowledge",
    "zk-proofs", "zk proofs", "confidential", "anonymous", "mixer",
    "private payments", "fully homomorphic", "fhe", "stealth address",
    "shielded", "privacy-preserving", "privacy chain", "private defi",
    "confidential computing", "tee", "trusted execution", /\bzk\b/,
  ],
  dn404: ["dn404", "dn-404", "dn 404"],
  "erc-8004": ["erc-8004", "erc8004", "8004"],
  identity: [
    "identity", "decentralized identity", "did", "self-sovereign identity",
    "ssi", "on-chain identity", "identity protocol", "verifiable credentials",
    "world id", "proof of personhood", "humanity proof", "sybil resistance",
    "identity layer", "passport", "web3 identity",
  ],
  payments: [
    "payments", "payment protocol", "payment rails", "on-chain payments",
    "crypto payments", "stablecoin payments", "remittance", "cross-border payments",
    "merchant payments", "payment infrastructure", "settlement layer",
    "instant settlement", "payfi",
  ],
  "info-fi": [
    "infofi", "info-fi", "information finance", "attention markets",
    "mindshare", "info finance", "knowledge markets", "signal markets",
  ],
  restaking: [
    "restaking", "restake", "restaked", "eigenlayer", "avs",
    "actively validated service", "shared security", "restaking layer",
  ],
  mev: [
    "mev", "maximal extractable", "mev protection", "mev-boost", "mev boost",
    "proposer builder", "pbs", "block builder", "flashbots",
  ],

  // ── Chain / ecosystem tags ──────────────────────────────────────────────
  // Matched primarily from bio/name text (projectTagger: name + description).
  // Prefer phrases over bare short tokens to avoid false positives (near/ton/base).
  // Also match @handles and $TICKERS when people put them in bios.
  ethereum: [
    "ethereum", "ethereum ecosystem", "on ethereum", "built on ethereum",
    "deployed on ethereum", "ethereum mainnet", "eth mainnet", "ethereum network",
    "ethereum foundation", "ethereum l1", "eth ecosystem", "built on eth",
    "on eth", "eth l1", "erc-20", "erc20", "erc-721", "erc721", "erc-1155",
    "erc1155", "solidity", "ethereum dapp", "ethereum protocol",
    "ethereum defi", "ethereum nft",
    "@ethereum",
    /\$eth\b/i,
  ],
  solana: [
    "solana", "on solana", "built on solana", "deployed on solana",
    "solana ecosystem", "solana network", "solana mainnet", "solana program",
    "solana dapp", "solana defi", "spl token", "spl tokens", "svm",
    "solana vm", "solana nft", "solana sealevel",
    "@solana",
    /\$sol\b/i,
  ],
  base: [
    "base chain", "base network", "base ecosystem", "on base", "built on base",
    "deployed on base", "base mainnet", "base l2", "coinbase l2",
    "base appchain", "base superchain", "base.org",
    "@base",
  ],
  arbitrum: [
    "arbitrum", "on arbitrum", "built on arbitrum", "arbitrum ecosystem",
    "arbitrum one", "arbitrum nova", "arbitrum orbit", "arb chain",
    "arbitrum l2", "stylus",
    "@arbitrum",
    /\$arb\b/i,
  ],
  optimism: [
    "optimism", "on optimism", "built on optimism", "optimism ecosystem",
    "op mainnet", "op stack", "opstack", "superchain", "optimism l2",
    "op chain",
    "@optimism",
    /\$op\b/i,
  ],
  polygon: [
    "polygon", "on polygon", "built on polygon", "polygon ecosystem",
    "polygon pos", "polygon zkevm", "polygon cdk", "matic network",
    "polygon chain",
    "@0xpolygon", "@polygon",
    /\$matic\b/i, /\$pol\b/i,
  ],
  bnb: [
    "bnb chain", "bnb smart chain", "binance smart chain", "bsc",
    "on bsc", "built on bsc", "built on bnb", "on bnb", "bnb ecosystem",
    "opbnb", "bnb greenfield",
    "@bnbchain",
    /\$bnb\b/i,
  ],
  avalanche: [
    "avalanche", "on avalanche", "built on avalanche", "avalanche ecosystem",
    "avax", "avax c-chain", "avalanche c-chain", "avalanche subnet",
    "@avax", "@avalancheavax",
    /\$avax\b/i,
  ],
  sui: [
    "sui network", "on sui", "built on sui", "sui ecosystem",
    "sui blockchain", "sui move", "sui mainnet", "sui chain",
    "@suinetwork", "@sui",
    /\$sui\b/i,
  ],
  aptos: [
    "aptos", "on aptos", "built on aptos", "aptos network", "aptos ecosystem",
    "aptos blockchain", "aptos move", "aptos mainnet",
    "@aptos",
    /\$apt\b/i,
  ],
  cosmos: [
    "cosmos", "cosmos sdk", "cosmos ecosystem", "ibc", "interchain",
    "cosmos hub", "appchain cosmos", "built with cosmos",
    "tendermint", "cometbft",
    "@cosmos",
    /\$atom\b/i,
  ],
  near: [
    "near protocol", "on near", "built on near", "near ecosystem",
    "near blockchain", "near mainnet", "near chain",
    "@nearprotocol",
    /\$near\b/i,
  ],
  ton: [
    "the open network", "on ton", "built on ton", "ton ecosystem",
    "ton blockchain", "toncoin", "telegram open network", "ton chain",
    "@ton_blockchain", "@toncoin",
    /\$ton\b/i,
  ],
  tron: [
    "tron", "on tron", "built on tron", "tron network", "tron ecosystem",
    "trc-20", "trc20", "tron blockchain",
    "@trondao", "@tronfoundation",
    /\$trx\b/i,
  ],
  berachain: [
    "berachain", "on berachain", "built on berachain", "bera chain",
    "berachain ecosystem", "proof of liquidity",
    "@berachain",
    /\$bera\b/i,
  ],
  monad: [
    "monad", "on monad", "built on monad", "monad chain", "monad ecosystem",
    "monad blockchain",
    "@monad_xyz", "@monad",
  ],
  starknet: [
    "starknet", "on starknet", "built on starknet", "starknet ecosystem",
    "starkware", "cairo", "starkex",
    "@starknet",
    /\$strk\b/i,
  ],
  zksync: [
    "zksync", "zk sync", "zk-sync", "on zksync", "built on zksync",
    "zksync era", "zksync ecosystem", "matter labs",
    "@zksync",
  ],
  scroll: [
    "scroll", "on scroll", "built on scroll", "scroll ecosystem",
    "scroll l2", "scroll zk", "scroll network",
    "@scroll_zkp", "@scroll",
  ],
  linea: [
    "linea", "on linea", "built on linea", "linea ecosystem", "linea l2",
    "consensys linea", "linea network",
    "@lineabuild",
  ],
  blast: [
    "blast l2", "on blast", "built on blast", "blast ecosystem",
    "blast network", "blast chain",
    "@blast",
  ],
  hyperliquid: [
    "hyperliquid", "on hyperliquid", "hyperliquid l1", "hyperliquid chain",
    "hyperliquid ecosystem", "hypercore",
    "@hyperliquidx",
    /\$hype\b/i,
  ],
};

/** Username delim tokens: match as (?:^|[_\\d])token(?:[_\\d]|$). */
export const HANDLE_TOKENS: Record<string, string[]> = {
  nft: ["nft", "art"],
  "nft-fi": ["nftfi"],
  ai: ["ai"],
  "ai-agents": ["agent", "agents"],
  defi: ["defi"],
  "dao-community": ["dao"],
  dex: ["dex", "swap"],
  meme: ["meme"],
  gamefi: ["gamefi", "gamer", "play", "mmo", "rpg", "game"],
  metaverse: ["meta"],
  socialfi: ["social"],
  wallet: ["wallet"],
  bridge: ["bridge"],
  rwa: ["rwa"],
  perps: ["perp", "perps"],
  lst: ["lst"],
  lrt: ["lrt"],
  vc: ["vc"],
  privacy: ["zk"],
  "btc-eco": ["btc"],
  l1: ["l1"],
  l2: ["l2"],
  depin: ["depin"],
  stablecoin: ["stable"],
  launchpad: ["pad", "launch"],
  predict: ["predict"],
  oracles: ["oracle"],
  identity: ["id", "did"],
  payments: ["pay"],
  // Official-style chain handles only (bio is the main source for chain tags)
  ethereum: ["ethereum"],
  solana: ["solana"],
  base: ["base"],
  arbitrum: ["arbitrum"],
  optimism: ["optimism"],
  polygon: ["polygon"],
  bnb: ["bnbchain"],
  avalanche: ["avalanche", "avax"],
  sui: ["sui"],
  aptos: ["aptos"],
  cosmos: ["cosmos"],
  near: ["nearprotocol"],
  ton: ["toncoin"],
  tron: ["tron"],
  berachain: ["berachain"],
  monad: ["monad"],
  starknet: ["starknet"],
  zksync: ["zksync"],
  scroll: ["scroll"],
  linea: ["linea"],
  blast: ["blast"],
  hyperliquid: ["hyperliquid"],
};

/** Username suffix tokens: handle.endsWith(token). */
export const HANDLE_SUFFIX_TOKENS: Record<string, string[]> = {
  nft: ["nft"],
  "dao-community": ["dao"],
  gamefi: ["gamefi", "play", "mmo", "rpg", "game"],
  socialfi: ["socialfi"],
  defi: ["defi"],
  defai: ["defai"],
  depin: ["depin"],
  dex: ["swap"],
  perps: ["perps"],
  meme: ["meme"],
  wallet: ["wallet"],
  ai: ["ai"],
  bridge: ["bridge"],
  launchpad: ["pad"],
  rwa: ["rwa"],
  // Prefer full names; short suffixes (eth/sol/arb) are too noisy
  ethereum: ["ethereum"],
  solana: ["solana"],
  arbitrum: ["arbitrum"],
  optimism: ["optimism"],
  polygon: ["polygon"],
  avalanche: ["avalanche"],
  berachain: ["berachain"],
  starknet: ["starknet"],
  zksync: ["zksync"],
  hyperliquid: ["hyperliquid"],
};
